version: '3.2'

services:
  access-point:
    image: access-point
    privileged: true
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus

  shairport-sync:
    image: shairport-sync
    privileged: true
    network_mode: host
    depends_on:
      - access-point
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp

  snapcast-server:
    image:  snapcast-server
    privileged: true
    network_mode: host
    depends_on:
      - shairport-sync
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp

  snapcast-client:
    image: snapcast-client
    privileged: true
    network_mode: host
    environment:
      SNAPCAST_SERVER_HOSTNAME: 127.0.0.1
      SOUNDCARD_ID: 24  # use 1 for default on-board audio out
    depends_on:
      - snapcast-server
    volumes:
      - /var/run/dbus:/var/run/dbus
    devices:
      - "/dev/snd/:/dev/snd/"

volumes:
  tmp-volume:
