version: '3.2'

services:
  shairport-sync:
    image: brandonfryslie/shairport-sync:latest
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp

  snapcast-server:
    image: brandonfryslie/snapcast-server:latest
    network_mode: host
    depends_on:
      - shairport-sync
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp

  snapcast-client:
    image: brandonfryslie/snapcast-client:latest
    network_mode: host
    environment:
      SNAPCAST_SERVER_HOSTNAME: snapcast-server
    volumes:
      - /var/run/dbus:/var/run/dbus
    depends_on:
      - snapcast-server
    devices:
      - "/dev/snd/:/dev/snd/"

volumes:
  tmp-volume:
