version: '3.2'

services:
  shairport-sync:
    image: shairport-sync
    privileged: true
    network_mode: host
    depends_on:
      - snapcast-server
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp

  snapcast-server:
    image:  snapcast-server
    privileged: true
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp

  snapcast-client:
    image:  snapcast-client
    privileged: true
    network_mode: host
    depends_on:
    - snapcast-server
    volumes:
      - /var/run/dbus:/var/run/dbus
      - tmp-volume:/tmp
    devices:
    - "/dev/snd/:/dev/snd/"

volumes:
  tmp-volume:
