---

- name: Add user to 'docker' group
  become: yes
  user:
    name: pi
    group: docker
    append: yes

#- name: Rsync repo to pi
#  synchronize:
#    src: '..'
#    dest: /home/pi/boom-waffle
#    recursive: yes
#    archive: yes

# Specifying a line w/o a regex parameter will append to the file
- name: Add pip packages to .bashrc
  lineinfile:
    dest: /home/pi/.bashrc
    line: 'export PATH="$PATH:/home/pi/.local/bin"'

# Specifying a line w/o a regex parameter will append to the file
- name: Disable wireless interface power saving mode
  become: yes
  lineinfile:
    dest: /etc/network/interfaces
    line: 'wireless-power off'
