---

- name: Add user to 'docker' group
  become: yes
  user:
    name: pi
    group: docker
    append: yes

# Specifying a line w/o a regex parameter will append to the file
- name: Add pip packages to .bashrc
  lineinfile:
    dest: /home/pi/.bashrc
    line: 'export PATH="$PATH:/home/pi/.local/bin"'
